root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  chapter/products: ./products.md

  chapter/gettingstarted: ./gettingstarted/introduction.md
  getting-started: ./gettingstarted/introduction.md
  getting-started/introduction: ./gettingstarted/introduction.md
  chapter/gettingstarted/introduction: ./gettingstarted/introduction.md
  chapter/gettingstarted/hardwaresetup: ./gettingstarted/connection/README.md
  chapter/gettingstarted/connection/lopy: ./gettingstarted/connection/lopy.md
  chapter/gettingstarted/connection/lopy4: ./gettingstarted/connection/lopy4.md
  chapter/gettingstarted/connection/sipy: ./gettingstarted/connection/sipy.md
  chapter/gettingstarted/connection/gpy: ./gettingstarted/connection/gpy.md
  chapter/gettingstarted/connection/fipy: ./gettingstarted/connection/fipy.md
  chapter/gettingstarted/connection/wipy: ./gettingstarted/connection/wipy.md
  chapter/gettingstarted/installation/installingsoftware: ./gettingstarted/installation/README.md
  chapter/gettingstarted/installation/drivers: ./gettingstarted/installation/drivers.md
  chapter/gettingstarted/installation/firmwaretool: ./gettingstarted/installation/firmwaretool.md
  chapter/gettingstarted/installation/pymakr: ./gettingstarted/installation/pymakr.md
  chapter/gettingstarted/programming: ./gettingstarted/programming/README.md
  chapter/gettingstarted/programming/micropython: ./gettingstarted/programming/micropython.md
  chapter/gettingstarted/programming/examples: ./gettingstarted/programming/examples.md
  chapter/gettingstarted/programming/first-project: ./gettingstarted/programming/first-project.md
  chapter/gettingstarted/programming/repl: ./gettingstarted/programming/repl/README.md
  chapter/gettingstarted/programming/repl/serial: ./gettingstarted/programming/repl/serial.md
  chapter/gettingstarted/programming/repl/telnet: ./gettingstarted/programming/repl/telnet.md
  chapter/gettingstarted/programming/ftp: ./gettingstarted/programming/ftp.md
  chapter/gettingstarted/programming/safeboot: ./gettingstarted/programming/safeboot.md
  chapter/gettingstarted/registration/README: ./gettingstarted/registration/README.md
  chapter/gettingstarted/registration/sigfox: ./gettingstarted/registration/sigfox.md
  chapter/gettingstarted/registration/cellular: ./gettingstarted/registration/cellular.md
  chapter/gettingstarted/registration/lora: ./gettingstarted/registration/lora/README.md
  chapter/gettingstarted/registration/lora/ttn: ./gettingstarted/registration/lora/ttn.md
  chapter/gettingstarted/registration/lora/objenious: ./gettingstarted/registration/lora/objenious.md

  chapter/pymakr/installation: ./pymakr/installation/README.md
  chapter/pymakr/installation/atom: ./pymakr/installation/atom.md
  chapter/pymakr/installation/vscode: ./pymakr/installation/vscode.md
  chapter/pymakr/toolsfeatures: ./pymakr/toolsfeatures.md
  chapter/pymakr/settings: ./pymakr/settings.md

  chapter/pytrackpysense: ./pytrackpysense/introduction.md
  chapter/pytrackpysense/installation: ./pytrackpysense/installation/README.md
  chapter/pytrackpysense/installation/firmware: ./pytrackpysense/installation/firmware.md
  chapter/pytrackpysense/installation/drivers: ./pytrackpysense/installation/drivers.md
  chapter/pytrackpysense/installation/libraries: ./pytrackpysense/installation/libraries.md
  chapter/pytrackpysense/apireference: ./pytrackpysense/apireference/README.md
  chapter/pytrackpysense/apireference/pytrack: ./pytrackpysense/apireference/pytrack.md
  chapter/pytrackpysense/apireference/pysense: ./pytrackpysense/apireference/pysense.md
  chapter/pytrackpysense/apireference/pyscan: ./pytrackpysense/apireference/pyscan.md
  chapter/pytrackpysense/apireference/sleep: ./pytrackpysense/apireference/sleep.md

  chapter/tutorials: ./tutorials/introduction.md
  chapter/tutorials/all: ./tutorials/all/README.md
  chapter/tutorials/all/repl: ./tutorials/all/repl.md
  chapter/tutorials/all/wlan: ./tutorials/all/wlan.md
  chapter/tutorials/all/ble: ./tutorials/all/ble.md
  chapter/tutorials/all/https: ./tutorials/all/https.md
  chapter/tutorials/all/mqtt: ./tutorials/all/mqtt.md
  chapter/tutorials/all/aws: ./tutorials/all/aws.md
  chapter/tutorials/all/adc: ./tutorials/all/adc.md
  chapter/tutorials/all/i2c: ./tutorials/all/i2c.md
  chapter/tutorials/all/owd: ./tutorials/all/owd.md
  chapter/tutorials/all/threading: ./tutorials/all/threading.md
  chapter/tutorials/all/rgbled: ./tutorials/all/rgbled.md
  chapter/tutorials/all/timers: ./tutorials/all/timers.md
  chapter/tutorials/all/pir: ./tutorials/all/pir.md
  chapter/tutorials/all/modbus: ./tutorials/all/modbus.md
  chapter/tutorials/all/ota: ./tutorials/all/ota.md
  chapter/tutorials/all/rmt: ./tutorials/all/rmt.md
  chapter/tutorials/all/socket: ./tutorials/all/socket.md
  chapter/tutorials/lora: ./tutorials/lora/README.md
  chapter/tutorials/lora/lora-mac: ./tutorials/lora/lora-mac.md
  chapter/tutorials/lora/lorawan-otaa: ./tutorials/lora/lorawan-otaa.md
  chapter/tutorials/lora/lorawan-abp: ./tutorials/lora/lorawan-abp.md
  chapter/tutorials/lora/lora-mac-nano-gateway: ./tutorials/lora/lora-mac-nano-gateway.md
  chapter/tutorials/lora/module-module: ./tutorials/lora/module-module.md
  chapter/tutorials/lora/lorawan-nano-gateway: ./tutorials/lora/lorawan-nano-gateway.md
  chapter/tutorials/lora/rn2483-to-lopy: ./tutorials/lora/rn2483-to-lopy.md
  chapter/tutorials/lora/lora-mesh: ./tutorials/lora/lora-mesh.md
  chapter/tutorials/sigfox: ./tutorials/sigfox.md
  chapter/tutorials/lte: ./tutorials/lte/README.md
  chapter/tutorials/lte/cat-m1: ./tutorials/lte/cat-m1.md
  chapter/tutorials/lte/nb-iot: ./tutorials/lte/nb-iot.md
  chapter/tutorials/lte/imei: ./tutorials/lte/imei.md
  chapter/tutorials/lte/firmware: ./tutorials/lte/firmware.md
  chapter/tutorials/pytrack: ./tutorials/pytrack.md
  chapter/tutorials/pysense: ./tutorials/pysense.md
  chapter/tutorials/pyscan: ./tutorials/pyscan.md

  chapter/firmwareapi: ./firmwareapi/introduction.md
  chapter/firmwareapi/pycom: ./firmwareapi/pycom/README.md
  chapter/firmwareapi/pycom/machine: ./firmwareapi/pycom/machine/README.md
  chapter/firmwareapi/pycom/machine/adc: ./firmwareapi/pycom/machine/adc.md
  chapter/firmwareapi/pycom/machine/dac: ./firmwareapi/pycom/machine/dac.md
  chapter/firmwareapi/pycom/machine/i2c: ./firmwareapi/pycom/machine/i2c.md
  chapter/firmwareapi/pycom/machine/pin: ./firmwareapi/pycom/machine/pin.md
  chapter/firmwareapi/pycom/machine/pwm: ./firmwareapi/pycom/machine/pwm.md
  chapter/firmwareapi/pycom/machine/rtc: ./firmwareapi/pycom/machine/rtc.md
  chapter/firmwareapi/pycom/machine/spi: ./firmwareapi/pycom/machine/spi.md
  chapter/firmwareapi/pycom/machine/uart: ./firmwareapi/pycom/machine/uart.md
  chapter/firmwareapi/pycom/machine/wdt: ./firmwareapi/pycom/machine/wdt.md
  chapter/firmwareapi/pycom/machine/timer: ./firmwareapi/pycom/machine/timer.md
  chapter/firmwareapi/pycom/machine/sd: ./firmwareapi/pycom/machine/sd.md
  chapter/firmwareapi/pycom/machine/can: ./firmwareapi/pycom/machine/can.md
  chapter/firmwareapi/pycom/machine/rmt: ./firmwareapi/pycom/machine/rmt.md
  chapter/firmwareapi/pycom/network: ./firmwareapi/pycom/network/README.md
  chapter/firmwareapi/pycom/network/wlan: ./firmwareapi/pycom/network/wlan.md
  chapter/firmwareapi/pycom/network/server: ./firmwareapi/pycom/network/server.md
  chapter/firmwareapi/pycom/network/bluetooth: ./firmwareapi/pycom/network/bluetooth/README.md
  chapter/firmwareapi/pycom/network/bluetooth/gatt: ./firmwareapi/pycom/network/bluetooth/gatt.md
  firmwareapi/pycom/network/bluetooth/gattcconnection: chapter/./firmwareapi/pycom/network/bluetooth/gattcconnection.md
  firmwareapi/pycom/network/bluetooth/gattccservice: chapter/./firmwareapi/pycom/network/bluetooth/gattccservice.md
  firmwareapi/pycom/network/bluetooth/gattccharacteristic: chapter/./firmwareapi/pycom/network/bluetooth/gattccharacteristic.md
  chapter/firmwareapi/pycom/network/bluetooth/gattsservice: ./firmwareapi/pycom/network/bluetooth/gattsservice.md
  firmwareapi/pycom/network/bluetooth/gattscharacteristic: chapter/./firmwareapi/pycom/network/bluetooth/gattscharacteristic.md
  chapter/firmwareapi/pycom/network/lora: ./firmwareapi/pycom/network/lora.md
  chapter/firmwareapi/pycom/network/sigfox: ./firmwareapi/pycom/network/sigfox.md
  chapter/firmwareapi/pycom/network/lte: ./firmwareapi/pycom/network/lte.md
  chapter/firmwareapi/pycom/aes: ./firmwareapi/pycom/aes.md
  chapter/firmwareapi/pycom/pycom: ./firmwareapi/pycom/pycom.md
  chapter/firmwareapi/micropython: ./firmwareapi/micropython/README.md
  chapter/firmwareapi/micropython/micropython: ./firmwareapi/micropython/micropython.md
  chapter/firmwareapi/micropython/uctypes: ./firmwareapi/micropython/uctypes.md
  chapter/firmwareapi/micropython/sys: ./firmwareapi/micropython/sys.md
  chapter/firmwareapi/micropython/uos: ./firmwareapi/micropython/uos.md
  chapter/firmwareapi/micropython/array: ./firmwareapi/micropython/array.md
  chapter/firmwareapi/micropython/cmath: ./firmwareapi/micropython/cmath.md
  chapter/firmwareapi/micropython/math: ./firmwareapi/micropython/math.md
  chapter/firmwareapi/micropython/gc: ./firmwareapi/micropython/gc.md
  chapter/firmwareapi/micropython/ubinascii: ./firmwareapi/micropython/ubinascii.md
  chapter/firmwareapi/micropython/ujson: ./firmwareapi/micropython/ujson.md
  chapter/firmwareapi/micropython/ure: ./firmwareapi/micropython/ure.md
  chapter/firmwareapi/micropython/usocket: ./firmwareapi/micropython/usocket.md
  chapter/firmwareapi/micropython/select: ./firmwareapi/micropython/select.md
  chapter/firmwareapi/micropython/utime: ./firmwareapi/micropython/utime.md
  chapter/firmwareapi/micropython/uhashlib: ./firmwareapi/micropython/uhashlib.md
  chapter/firmwareapi/micropython/ussl: ./firmwareapi/micropython/ussl.md
  chapter/firmwareapi/micropython/ucrypto: ./firmwareapi/micropython/ucrypto.md
  chapter/firmwareapi/micropython/ustruct: ./firmwareapi/micropython/ustruct.md
  chapter/firmwareapi/micropython/uzlib: ./firmwareapi/micropython/uzlib.md
  chapter/firmwareapi/micropython/_thread: ./firmwareapi/micropython/_thread.md
  chapter/firmwareapi/micropython/builtin: ./firmwareapi/micropython/builtin.md
  chapter/firmwareapi/notes: ./firmwareapi/notes.md

  product-info: ./datasheets/introduction.md
  product-info/development: ./datasheets/development/README.md
  product-info/development/wipy2: ./datasheets/development/wipy2.md
  product-info/development/wipy3: ./datasheets/development/wipy3.md
  product-info/development/lopy: ./datasheets/development/lopy.md
  product-info/development/lopy4: ./datasheets/development/lopy4.md
  product-info/development/sipy: ./datasheets/development/sipy.md
  product-info/development/gpy: ./datasheets/development/gpy.md
  product-info/development/fipy: ./datasheets/development/fipy.md
  product-info/oem: ./datasheets/oem/README.md
  product-info/oem/w01: ./datasheets/oem/w01.md
  product-info/oem/l01: ./datasheets/oem/l01.md
  product-info/oem/l04: ./datasheets/oem/l04.md
  product-info/oem/g01: ./datasheets/oem/g01.md
  product-info/oem/l01_reference: ./datasheets/oem/l01_reference.md
  product-info/oem/universal_reference: ./datasheets/oem/universal_reference.md
  product-info/boards: ./datasheets/boards/README.md
  product-info/boards/expansion3: ./datasheets/boards/expansion3.md
  product-info/boards/pytrack: ./datasheets/boards/pytrack.md
  product-info/boards/pysense: ./datasheets/boards/pysense.md
  product-info/boards/pyscan: ./datasheets/boards/pyscan.md
  product-info/boards/expansion2: ./datasheets/boards/expansion2.md
  product-info/boards/deepsleep: ./datasheets/boards/deepsleep/README.md
  product-info/boards/deepsleep/api: ./datasheets/boards/deepsleep/api.md
  product-info/notes: ./datasheets/notes.md

  chapter/datasheets: ./datasheets/introduction.md
  chapter/datasheets/development: ./datasheets/development/README.md
  chapter/datasheets/development/wipy2: ./datasheets/development/wipy2.md
  chapter/datasheets/development/wipy3: ./datasheets/development/wipy3.md
  chapter/datasheets/development/lopy: ./datasheets/development/lopy.md
  chapter/datasheets/development/lopy4: ./datasheets/development/lopy4.md
  chapter/datasheets/development/sipy: ./datasheets/development/sipy.md
  chapter/datasheets/development/gpy: ./datasheets/development/gpy.md
  chapter/datasheets/development/fipy: ./datasheets/development/fipy.md
  chapter/datasheets/oem: ./datasheets/oem/README.md
  chapter/datasheets/oem/w01: ./datasheets/oem/w01.md
  chapter/datasheets/oem/l01: ./datasheets/oem/l01.md
  chapter/datasheets/oem/l04: ./datasheets/oem/l04.md
  chapter/datasheets/oem/g01: ./datasheets/oem/g01.md
  chapter/datasheets/oem/l01_reference: ./datasheets/oem/l01_reference.md
  chapter/datasheets/oem/universal_reference: ./datasheets/oem/universal_reference.md
  chapter/datasheets/boards: ./datasheets/boards/README.md
  chapter/datasheets/boards/expansion3: ./datasheets/boards/expansion3.md
  chapter/datasheets/boards/pytrack: ./datasheets/boards/pytrack.md
  chapter/datasheets/boards/pysense: ./datasheets/boards/pysense.md
  chapter/datasheets/boards/pyscan: ./datasheets/boards/pyscan.md
  chapter/datasheets/boards/expansion2: ./datasheets/boards/expansion2.md
  chapter/datasheets/boards/deepsleep: ./datasheets/boards/deepsleep/README.md
  chapter/datasheets/boards/deepsleep/api: ./datasheets/boards/deepsleep/api.md
  chapter/datasheets/notes: ./datasheets/notes.md

  chapter/pybytes: ./pybytes/introduction.md
  chapter/pybytes/getstarted/intro: ./pybytes/getstarted.md
  chapter/pybytes/connect/intro: ./pybytes/connect/README.md
  chapter/pybytes/connect/quick: ./pybytes/connect/quick.md
  chapter/pybytes/connect/flash: ./pybytes/connect/flash.md
  chapter/pybytes/connect/sigfox/sigfox: ./pybytes/connect/sigfox/README.md
  chapter/pybytes/connect/sigfox/sigfoxDevKit: ./pybytes/connect/sigfox/devkit.md
  chapter/pybytes/connect/sigfox/sigfoxCustomContract: ./pybytes/connect/sigfox/custom.md
  chapter/pybytes/dashboard/intro: ./pybytes/dashboard

  chapter/docnotes: ./docnotes/introduction.md
  chapter/docnotes/syntax: ./docnotes/syntax.md
  chapter/docnotes/replscript: ./docnotes/replscript.md
  chapter/docnotes/mesh-networks: ./docnotes/mesh-networks.md

  chapter/advance/downgrade: ./advance/downgrade.md
  chapter/advance/cli: ./advance/cli.md
  chapter/advance/encryption: ./advance/encryption.md

  chapter/license: ./license.md
